### ISSUE TITLE
Blocked Flute sound in tutorial

### ISSUE THREAD

**Issue by lupoDharkael** [pigdevstudio/bard-lesson#11]
When the hand is pressing the buttons, if you skip the part of the tutorial pressing Enter just right after the sound is emitted, you can hear how it keeps playing because the release of the button didn't happen.

**Comment by henriiquecampos** [comment]
Hey, thanks for the report. I think is just a matter of call `stop` on the `$Flute.SFX` in the next part of the tutorial, I'll fix this soon.
