### ISSUE TITLE
Player's character not falling 

### ISSUE THREAD

**Issue by lupoDharkael** [pigdevstudio/bard-lesson#12]
If you try to play the flute while you are falling, the character will stay in the air while you play the sound.
Note:  this doesn't happen if you are falling from a jump, you need to fall from the border of a platform.

**Comment by henriiquecampos** [comment]
~~This is a feature~~  lol

Thank you very much for the report, I think this:

```
event.is_action_pressed("interact") and is_on_floor()
```
instead of this:

```
if event.is_action_pressed("interact") and current_state != JUMP:
```

I already made the change on [hotfixes branch](https://github.com/pigdevstudio/bard-lesson/tree/hotfixes) if you use Godot, please do check it out 🐷

**Comment by lupoDharkael** [comment]
I've tested it and it's fixed!
