### ISSUE TITLE
Handle button logic depending on keyboard layout

### ISSUE THREAD

**Issue by pwab** [pigdevstudio/bard-lesson#8]
When working with other keyboard layouts the chars for playing the sound are not always in a row which makes it a bit hard to play. E.g. the german/austrian layout called QWERTZ has swapped the `y` and `z` keys. See [here](https://en.wikipedia.org/wiki/Keyboard_layout#QWERTZ) for reference.

It could be handled automatically or at least with manually configuring the buttons used to play.

_PS:
This game has some beautiful art, well picked sounds and the movement feels very smooth. Congrats!_

**Comment by henriiquecampos** [comment]
Ohh of course I missed this, what do you think about this: at the time the tutorial presents the flute, it will only explain the pitches showing 3 blank keys in a row.

When the player test the flute it will map the keys to the action. This way before the game starts the player will automatically set his/her own bindings

**Comment by pwab** [comment]
This sounds interesting. It should be clear to the player that this will be some kind of configuration but all in all I like the concept. :+1:

**Comment by williamd1k0** [comment]
There is a method to check the kb layout.
API docs: http://docs.godotengine.org/en/3.0/classes/class_os.html#class-os-get-latin-keyboard-variant

Note: The QWERTZ layout was not mentioned in the docs for some reason but it exists in the API.

https://github.com/godotengine/godot/blob/7a142780f05d56aa751690c8716bd8aab429b140/core/bind/core_bind.cpp#L438

**Comment by pwab** [comment]
Yeah it could be configured automatically but you'll have to write some _char-button-assignment_-logic depending on the kb layout.

> Note: The QWERTZ layout was not mentioned in the docs for some reason but it exists in the API.
>
> https://github.com/godotengine/godot/blob/7a142780f05d56aa751690c8716bd8aab429b140/core/bind/core_bind.cpp#L438

Thanks for pointing this out! Would you mind creating an issue in the docs repo?

**Comment by henriiquecampos** [comment]
Gotta get in touch with the guys from Godot Engine, I think the logic will be the same as they do to configure custom actions in the project.

**Comment by henriiquecampos** [comment]
Well, I implemented this new approach at #10 tell me what do you think.

The controls got even snappy by using `_input` instead of `_process`. Hope this gives a better experience
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10171059/37056298-c591e320-2162-11e8-98ea-d9ad25e6a4c8.gif)

**Comment by pwab** [comment]
I tested it a bit with kind of fuzzing and I totally broke your game with:

- Pressing SKIP and NEXT until the tutorial is over and the player is not able to play anything
- Press the arrow keys and space bar until no other key inputs (like z, x, c) are accepted
- Press some special keys like ä, ö, ü or STRG + something to get some fancy UI:

![o](https://user-images.githubusercontent.com/19271185/37063552-08f3398e-219a-11e8-962b-bc4a131eadcf.png)

Still love it though :)

**Comment by henriiquecampos** [comment]
omg lol 
hmm I think there's a way to filter modifiers, like <kbd>ctrl</kbd> or <kbd>shift</kbd> but...man I'm very inclined to ostrich this. But I'll surely give a try. Still laughing tho lol
